name: Docker Build and Push

on:
  push:
    branches: [ master, staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Log in to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract branch name
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        tags: ghcr.io/johnthenerd/homeassistant-llm-prompt-generator:${{ env.BRANCH_NAME }}